package com.example.footballseasonsimulator.config;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import org.springframework.context.annotation.Configuration;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * Metrics configuration for monitoring the football simulation.
 * 
 * <p>Exposes the following metrics:
 * <ul>
 *   <li><b>simulation.matches.completed</b> - Counter of completed matches</li>
 *   <li><b>simulation.goals.scored</b> - Counter of goals scored</li>
 *   <li><b>simulation.events.generated</b> - Counter of events generated by type</li>
 *   <li><b>simulation.active.leagues</b> - Gauge of active league simulations</li>
 *   <li><b>simulation.websocket.connections</b> - Gauge of active WebSocket connections</li>
 *   <li><b>simulation.match.duration</b> - Timer for match simulation duration</li>
 * </ul>
 */
@Configuration
public class MetricsConfig {

    private final MeterRegistry meterRegistry;
    
    // Atomic counters for gauges
    private final AtomicInteger activeLeagues = new AtomicInteger(0);
    private final AtomicInteger websocketConnections = new AtomicInteger(0);

    public MetricsConfig(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
        registerGauges();
    }

    private void registerGauges() {
        Gauge.builder("simulation.active.leagues", activeLeagues, AtomicInteger::get)
                .description("Number of active league simulations")
                .register(meterRegistry);

        Gauge.builder("simulation.websocket.connections", websocketConnections, AtomicInteger::get)
                .description("Number of active WebSocket connections")
                .register(meterRegistry);
    }

    /**
     * Get counter for completed matches.
     */
    public Counter matchesCompletedCounter() {
        return Counter.builder("simulation.matches.completed")
                .description("Total number of completed matches")
                .register(meterRegistry);
    }

    /**
     * Get counter for goals scored.
     */
    public Counter goalsCounter() {
        return Counter.builder("simulation.goals.scored")
                .description("Total number of goals scored")
                .register(meterRegistry);
    }

    /**
     * Get counter for events by type.
     */
    public Counter eventsCounter(String eventType) {
        return Counter.builder("simulation.events.generated")
                .tag("type", eventType)
                .description("Number of events generated by type")
                .register(meterRegistry);
    }

    /**
     * Get timer for match simulation duration.
     */
    public Timer matchDurationTimer() {
        return Timer.builder("simulation.match.duration")
                .description("Time taken to simulate a match")
                .register(meterRegistry);
    }

    /**
     * Get timer for fixture simulation duration.
     */
    public Timer fixtureDurationTimer() {
        return Timer.builder("simulation.fixture.duration")
                .description("Time taken to simulate a fixture (matchweek)")
                .register(meterRegistry);
    }

    /**
     * Increment active leagues count.
     */
    public void incrementActiveLeagues() {
        activeLeagues.incrementAndGet();
    }

    /**
     * Decrement active leagues count.
     */
    public void decrementActiveLeagues() {
        activeLeagues.decrementAndGet();
    }

    /**
     * Set active leagues count.
     */
    public void setActiveLeagues(int count) {
        activeLeagues.set(count);
    }

    /**
     * Increment WebSocket connections count.
     */
    public void incrementWebsocketConnections() {
        websocketConnections.incrementAndGet();
    }

    /**
     * Decrement WebSocket connections count.
     */
    public void decrementWebsocketConnections() {
        websocketConnections.decrementAndGet();
    }

    /**
     * Get current WebSocket connections count.
     */
    public int getWebsocketConnectionsCount() {
        return websocketConnections.get();
    }
}

